### ISSUE TITLE
 `System.GetOwnSystemAsync()`: Invalid description 'EW' for enum Orientation

### ISSUE THREAD

**Issue by CodeCasterNL** [pyrocumulus/pvoutput.net#129]
#### Describe the bug
The orientation "EW" isn't known (https://github.com/pyrocumulus/pvoutput.net/blob/develop/src/PVOutput.Net/Enums/Orientation.cs).

#### To reproduce
1. Set up client
1. Configure PVOutput panel orientation "EW"
1. Call method `System.GetOwnSystemAsync()`
1. See error

#### Stack Trace
```bash
System.ArgumentException: Invalid description 'EW' for enum Orientation (Parameter 'enumerationDescription')
   at PVOutput.Net.Objects.Core.FormatHelper.DescriptionToEnumValue[TEnumType](String enumerationDescription)
   at PVOutput.Net.Objects.Modules.Readers.SystemObjectStringReader.<>c.<ParseBaseProperties>b__2_9(ISystem t, String s)
   at PVOutput.Net.Objects.Core.BaseObjectStringReader`1.ParsePropertyArray(TReturnType target, TextReader reader, Action`2[] properties)
   at PVOutput.Net.Objects.Modules.Readers.SystemObjectStringReader.ParseBaseProperties(ISystem target, TextReader reader)
   at PVOutput.Net.Objects.Core.BaseObjectStringReader`1.ParseProperties(TReturnType target, TextReader reader, CancellationToken cancellationToken)
   at PVOutput.Net.Objects.Core.BaseObjectStringReader`1.ReadObjectAsync(TextReader reader, CancellationToken cancellationToken)
   at PVOutput.Net.Objects.Core.BaseObjectStringReader`1.ReadObjectAsync(Stream stream, CancellationToken cancellationToken)
   at PVOutput.Net.Requests.Handler.RequestHandler.ExecuteSingleItemRequestAsync[TResponseContentType](IRequest request, Dictionary`2 loggingScope, CancellationToken cancellationToken)
```

Undocumented though: https://pvoutput.org/help/api_specification.html#id66

**Comment by pyrocumulus** [comment]
It makes sense in the context of solar panels, but I simply reflected the compass rose in the library. Thankfully it's also undocumented, which makes me feel a little bit better ;)

You can expect a release somewhere this coming weekend.
